### ISSUE TITLE
about poisoned graph in polblogs

### ISSUE THREAD

**Issue by lzh-nwpu** [RinneSz/CLGA#1]
Hi, RinneSz

I've already run your code,but i don't know how to generate poisoned graphs in the dataset polblogs(Cora and CiteSeer is successful).How can I do to generate it?

**Comment by RinneSz** [comment]
I recommend you to upgrade the version of torch_geometric to >=2.0.3, so that you can simply download and use PolBlogs with torch_geometric.datasets.PolBlogs. Add it to the get_dataset() function in dataset.py should work.

**Comment by lzh-nwpu** [comment]
Thank you, RinneSz. That problem has been solved. Well anothor question is how to run train_GCA.py for downstream task link prediction? I just run it for node classfication successfully. What can I do?

**Comment by RinneSz** [comment]
I have uploaded train_LP.py for link prediction. You can check it.

**Comment by lzh-nwpu** [comment]
Thank you, RinneSz. Could you upload the code of visualization? I don't know some parameters about the t-SNE.

**Comment by RinneSz** [comment]
Just use the TSNE function in sklearn. You can find a large number of tutorials online.
