### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by xiangxinchufa** [RinneSz/CLGA#3]
作者你好：
         我在运行CLGA.py时出现如下错误，我应该如何解决，期待你的回答！
Perturbing edges: 50/527. Finished in 8.24s
Perturbing edges: 51/527. Finished in 8.91s
Perturbing edges: 52/527. Finished in 9.18s
Traceback (most recent call last):
  File "C:\Users\zhangqi\Desktop\CLGA-main\CLGA.py", line 243, in <module>
    poisoned_adj = model.attack()
  File "C:\Users\zhangqi\Desktop\CLGA-main\CLGA.py", line 147, in attack
    pkl.dump(output_adj.to(torch.device('cpu')), open('poisoned_adj/%s_CLGA_0.010000_adj.pkl' % args.dataset, 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: 'poisoned_adj/Cora_CLGA_0.010000_adj.pkl'

**Comment by RinneSz** [comment]
在根目录下新建一个名为poisoned_adj的文件夹就可以解决这个问题
