### ISSUE TITLE
运行没有结果输出

### ISSUE THREAD

**Issue by qscfthm** [RinneSz/CLGA#4]
作者您好，我在生成中毒图的时候，即运行python CLGA.py --dataset Cora --num_epochs 3000 --device cuda:0之后没有任何结果输出，将epoch改到很低也一直未输出任何内容，请问您了解这是什么情况吗，您训练一遍大约需要多少时间呢

**Comment by RinneSz** [comment]
您在运行CLGA.py之后有任何报错信息或者print出任何文字吗

**Comment by qscfthm** [comment]
是的，代码可能一直在运行（并未退出）但一直也未显示任何内容

**Comment by qscfthm** [comment]
没有显示任何内容也未退出   代码可能一直在运行但一直也未显示任何内容

**Comment by RinneSz** [comment]
也许是因为网络问题导致从torch geometric下载数据集失败，您可以验证一下是否是这个问题并尝试更换网络

**Comment by xiangxinchufa** [comment]
感谢作者的回复，我在运行程序也遇到了相同的问题；应该不是下载数据集失败的问题，我尝试在main函数的第一句添加print也是没有反应，程序运行感觉就没有进入main函数；既不报错，也没反应，不知道作者在运行时有无遇到相同的问题，期待回复！

**Comment by RinneSz** [comment]
重新确认了一遍，我这里没有这个问题，代码能正常运行。请你检查一下代码是否卡在了最上面的import语句处

**Comment by xiangxinchufa** [comment]
谢谢作者的及时回复，想问一下作者是在什么样的GPU环境运行的？

**Comment by RinneSz** [comment]
在多台有不同GPU的服务器上测试过

**Comment by HotBento** [comment]
我也遇到了这个问题，测试后发现程序是卡在了CLGA.py文件中`from pGRACE.dataset import get_dataset`这一行。但当我以debug模式运行时，代码又能够正常运行了。之后我将
```python
from pGRACE.functional import drop_feature, drop_edge_weighted, \
    degree_drop_weights, evc_drop_weights, pr_drop_weights, \
    feature_drop_weights, drop_feature_weighted, feature_drop_weights_dense
from pGRACE.utils import get_activation, compute_pr, eigenvector_centrality
from pGRACE.dataset import get_dataset
```
这三行与pGraph有关的import代码移动到代码开头位置后程序就能成功运行了（我也不知道为什么，网上也没能搜到相似的情况）。如果遇到这一问题可以尝试：
1、使用print确定卡在哪行import处；
2、将那行import移动到代码开头。
