### ISSUE TITLE
Transferability of attacks on Cora for DeepWalk and GCN.

### ISSUE THREAD

**Issue by Tianbaojie** [RinneSz/CLGA#5]
Table 4: Transferability of attacks on Cora for DeepWalk and GCN: How to reproduce the results of this part of the experiment, I didn't find the relevant code.

**Comment by RinneSz** [comment]
This part is quite simple so it is not uploaded to this repository. You can simply use the poisoned adjacency matrices to train a DeepWalk or GCN model, which can be written by yourself or any available python packages such as torch geometric.

**Comment by Tianbaojie** [comment]
我对torch geometric不是很熟悉，还请大佬把这部分的代码发我邮箱一份tbj0709@gmail.com,救救孩子吧，呜呜呜呜

**Comment by RinneSz** [comment]
Using DeepRobust package is more convenient, try the example here https://deeprobust.readthedocs.io/en/latest/source/deeprobust.graph.defense.html?highlight=deepwalk#deeprobust.graph.defense.DeepWalk.deepwalk_skipgram
